
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranav
 */
public class DelBook extends javax.swing.JFrame {

    /**
     * Creates new form DelBook
     */
    public DelBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DELETE BOOKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 168, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DELETE using :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bookname", "BookId", "Author", "Publication", " " }));
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, 30));

        tf1.setText("Enter record to be deleted");
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf1FocusGained(evt);
            }
        });
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 310, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusGained
        // TODO add your handling code here:
        tf1.setText("");
    }//GEN-LAST:event_tf1FocusGained
String choice,search;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // Object[] empty = {"","","","",""};
        choice = (String)cb1.getSelectedItem();
        search = tf1.getText();
            String connectionURL = "jdbc:mysql://localhost:3306/libProj";
            //ConnectionURL, username and password should be specified in getConnection()
         switch(choice)
          {
            case "Bookname" : { try {
                                System.out.println("Works");
                                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                                String sql = "DELETE FROM books where bname = '"+search+"'";
                                Statement st = conn.createStatement();
                                st.executeUpdate(sql);
                                 st.close();
                                 conn.close();
                                 jp1.showMessageDialog(null,"Deleted!");
                                  } 
                                 catch (SQLException ex) {
                                  jp1.showMessageDialog(null,ex);}}
                               break;
            case "Book.ID" : { try {
                                int bid = Integer.parseInt(search);
                                System.out.println("Works");
                                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                                String sql = "DELETE FROM books where BID = '"+search+"'";
                                Statement st = conn.createStatement();
                                st.executeUpdate(sql);
                                 st.close();
                                 conn.close();
                                 jp1.showMessageDialog(null,"Deleted!");
                                  } 
                                 catch (SQLException ex) {
                                  jp1.showMessageDialog(null,ex);}}
                                 break;
            case "Author" : { try {
                                System.out.println("Works");
                                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                                String sql = "DELETE FROM books where author = '"+search+"'";
                                Statement st = conn.createStatement();
                                st.executeUpdate(sql);
                                 st.close();
                                 conn.close();
                                 jp1.showMessageDialog(null,"Deleted!");
                                  } 
                                 catch (SQLException ex) {
                                  jp1.showMessageDialog(null,ex);}}
                                 break;
            case "Publication" : { try { 
                                System.out.println("Works");
                                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                                String sql = "DELETE FROM books where pub = '"+search+"'";
                                Statement st = conn.createStatement();
                                st.executeUpdate(sql);
                                 st.close();
                                 conn.close();
                                 jp1.showMessageDialog(null,"Deleted!");
                                  } 
                                 catch (SQLException ex) {
                                  jp1.showMessageDialog(null,ex);}}
           
           
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminHome a = new adminHome();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jPanel1.setBackground(Color.yellow);         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated
String name,snof,author,pub;
int sno;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JOptionPane jp1;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
