/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
/**
 *
 * @author pranav
 */
public class UPBook extends javax.swing.JFrame {

    /**
     * Creates new form UPBook
     */
    public UPBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l0 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        tf0 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        l11 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EDIT BOOK DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 200, 27));
        jPanel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 31));
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 28));
        jPanel1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 170, 32));

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("UPDATE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 165, 81, 31));

        l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l1.setText("BOOK NAME:");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 28));

        l0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l0.setText("Book ID:");
        jPanel1.add(l0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 24));

        l2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l2.setText("ISBN:");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 30));

        tf0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf0KeyReleased(evt);
            }
        });
        jPanel1.add(tf0, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 167, 26));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 85, 34));

        l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l3.setText("AUTHOR:");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 28));

        l4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l4.setText("PUBLISHER:");
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 32));
        jPanel1.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 28));

        l5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l5.setText("PUBKISHING YEAR:");
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, 28));
        jPanel1.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, 28));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));
        jPanel1.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf6KeyReleased(evt);
            }
        });
        jPanel1.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 68, 167, 26));

        l6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6.setText("ENTER BOOK I.D:");
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminHome h= new adminHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
String bname,isbn,author,pub,id;
int pubyr;
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        bname = tf1.getText();
        id = tf0.getText();
        isbn = tf2.getText();
        author = tf3.getText();
        pub = tf4.getText();
        pubyr=Integer.parseInt(tf5.getText());
        try{
            if(!"".equals(bname)&&!"".equals(author)&& !"".equals(pub)&& !"".equals(isbn) && pubyr!=0 )
            {
                String connectionURL = "jdbc:mysql://localhost:3306/libProj";
//ConnectionURL, username and password should be specified in getConnection()
                 try {
                     Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                     String sql = "UPDATE books SET bname='"+bname+"',bid ='"+id+"', isbn = '"+isbn+"',author = '"+author+"',pub ='"+pub+"',pubyr ="+pubyr+" where bid = '"+bid+"'";
                     Statement st = conn.createStatement();
                     st.executeUpdate(sql);
                     st.close();
                     conn.close();
                     jp1.showMessageDialog(null,"Updated!");
                     tf0.setText("");
                     tf1.setText("");
                     tf2.setText("");
                     tf3.setText("");
                     tf4.setText("");
                     tf5.setText("");
                     } catch (SQLException ex) {
                     System.out.println("Connect failed ! ");
                     }
            }
            else
            {
                jp1.showMessageDialog(null,"Empty Field");
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
            }
        }
        catch(Exception e){jp1.showMessageDialog(null,e);}
    }//GEN-LAST:event_b1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jPanel1.setBackground(Color.yellow);    
    // TODO add your handling code here:
        tf1.setEnabled(false);
        tf2.setEnabled(false);
        tf3.setEnabled(false);
        tf4.setEnabled(false);
        tf5.setEnabled(false);
        l1.setEnabled(false);
        l2.setEnabled(false);
        l3.setEnabled(false);
        l4.setEnabled(false);
        l5.setEnabled(false);
        b1.setEnabled(false);
        tf0.setEnabled(false);
        l0.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void tf0KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf0KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf0KeyReleased
String bid ,is;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int flag =0;
        bid = tf6.getText();
        String connectionURL = "jdbc:mysql://localhost:3306/libProj";
            //ConnectionURL, username and password should be specified in getConnection()
            try {
                System.out.println("Works");
                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                String sql = "SELECT * FROM books";
                Statement st = conn.createStatement();
                ResultSet rs=null;
                rs=st.executeQuery(sql);
                while(rs.next()){
                    //System.out.println(rs.getString("sname")+"\t"+rs.getString("dept"));
                    is = rs.getString("BID");
                    if(bid.equalsIgnoreCase(is))
                        flag=1;
                }
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException ex) {
                jp1.showMessageDialog(null,ex);

            }
    if(flag >= 1)
    { tf1.setEnabled(true);
        tf2.setEnabled(true);
        tf3.setEnabled(true);
        tf4.setEnabled(true);
        tf5.setEnabled(true);
        l1.setEnabled(true);
        l2.setEnabled(true);
        l3.setEnabled(true);
        l4.setEnabled(true);
        l5.setEnabled(true);
        b1.setEnabled(true);
        l0.setEnabled(true);
        tf0.setEnabled(true);}
   else
    {
      jp1.showMessageDialog(null,"Wrong Book ID!");
      //jp1.showMessageDialog(null,is);

    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JOptionPane jp1;
    private javax.swing.JLabel l0;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField tf0;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
