
import java.awt.Color;
import java.awt.Image;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pranav
 */
public class Upstud extends javax.swing.JFrame {

    /**
     * Creates new form Upstud
     */
    public Upstud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        tf0 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        l11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("UPDATE STUDENT RECORDS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 267, 27));
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("UPDATE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 81, 31));

        l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l1.setText("STUDENT NAME:");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 143, 120, -1));
        jPanel1.add(tf0, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 143, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ENTER REGISTER NUMBER:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 173, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("O.K");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 31));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 85, 34));

        l2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l2.setText("YEAR :");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 28));

        l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l3.setText("SECTION: ");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        l4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l4.setText("BOOKS TAKEN:");
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 20));
        jPanel1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 190, -1));
        jPanel1.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD YEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        jPanel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 190, -1));

        l5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l5.setText("REGISTER NUMBER:");
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 30));
        jPanel1.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, -1));
        jPanel1.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userHome h= new userHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
int year;
String name,sec,books,rno;
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        name = tf1.getText();
        year = Integer.parseInt(tf2.getText());
        sec = tf3.getText();
        books = tf4.getText();
        rno = tf5.getText();
        String connectionURL = "jdbc:mysql://localhost:3306/libProj";
//ConnectionURL, username and password should be specified in getConnection()
                 try {
                     Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                     String sql = "UPDATE student SET NAME='"+name+"',regno='"+rno+"', year = "+year+",sec = '"+sec+"' where regno= '"+regno+"'";
                     Statement st = conn.createStatement();
                     st.executeUpdate(sql);
                     st.close();
                     conn.close();
                     } catch (SQLException ex) {
jp1.showMessageDialog(null,ex);                     }
    }//GEN-LAST:event_b1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jPanel1.setBackground(Color.yellow);         // TODO add your handling code here:
        tf1.setEnabled(false);
        tf2.setEnabled(false);
        tf3.setEnabled(false);
        tf4.setEnabled(false);
        l1.setEnabled(false);
        l2.setEnabled(false);
        l3.setEnabled(false);
        l4.setEnabled(false);
        b1.setEnabled(false);
        l5.setEnabled(false);
        tf5.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated
String regno;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        regno = tf0.getText();
        String reg;
        int flag = 0;
        String connectionURL = "jdbc:mysql://localhost:3306/libProj";
            //ConnectionURL, username and password should be specified in getConnection()
            try {
                System.out.println("Works");
                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                String sql = "SELECT * FROM student";
                Statement st = conn.createStatement();
                ResultSet rs=null;
                rs=st.executeQuery(sql);
                while(rs.next()){
                    //System.out.println(rs.getString("sname")+"\t"+rs.getString("dept"));
                    reg = rs.getString("regno");
                    if(regno.equals(reg))
                        flag=1;
                }
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException ex) {
                jp1.showMessageDialog(null,ex);

            }
    if(flag == 1)
    { tf1.setEnabled(true);
        tf2.setEnabled(true);
        tf3.setEnabled(true);
        tf4.setEnabled(true);
        l1.setEnabled(true);
        l2.setEnabled(true);
        l3.setEnabled(true);
        l4.setEnabled(true);
        b1.setEnabled(true);
        l5.setEnabled(true);
        tf5.setEnabled(true);
                            }
   else
    {
      jp1.showMessageDialog(null,"Wrong Registration number!");
      tf0.setText("");
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String connectionURL = "jdbc:mysql://localhost:3306/libProj";
//ConnectionURL, username and password should be specified in getConnection()
                 try {
                     Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                     String sql = "UPDATE student SET year = year+1;";
                     Statement st = conn.createStatement();
                     st.executeUpdate(sql);
                     st.close();
                     conn.close();
                     } catch (SQLException ex) {
                     System.out.println("Connect failed ! ");
                     }
                 try {
                System.out.println("Works");
                Connection conn = DriverManager.getConnection(connectionURL, "root", "sairam");
                String sql = "DELETE FROM student where year >4;";
                Statement st = conn.createStatement();
                st.executeUpdate(sql);
                st.close();
                conn.close();
                jp1.showMessageDialog(null,"Updated!");
            } 
        catch (SQLException ex) {
                jp1.showMessageDialog(null,ex);}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upstud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JOptionPane jp1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField tf0;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
